component:
    id: 16
benchmark:
    type: 6
    relativeUrl: /
sourceCode:
    entryPoint: public/index.php
    urls:
        jsonSerialization: 'https://github.com/phpbenchmarks/symfony-json-serializer/blob/5.0.5_json-serialization-hello-world_0/public/index.php'
coreDependency:
    name: symfony/serializer
    version: 5.0.5
