component:
    id: 16
benchmark:
    type: 7
    relativeUrl: /
sourceCode:
    entryPoint: public/index.php
    urls:
        jsonSerialization: 'https://github.com/phpbenchmarks/symfony-json-serializer/blob/5.0.6_json-serialization-small-overload_0/public/index.php#L27'
        integerSerialization: 'https://github.com/phpbenchmarks/symfony-json-serializer/blob/5.0.6_json-serialization-small-overload_0/public/index.php#L27'
        floatSerialization: 'https://github.com/phpbenchmarks/symfony-json-serializer/blob/5.0.6_json-serialization-small-overload_0/public/index.php#L27'
        stringSerialization: 'https://github.com/phpbenchmarks/symfony-json-serializer/blob/5.0.6_json-serialization-small-overload_0/public/index.php#L27'
        booleanSerialization: 'https://github.com/phpbenchmarks/symfony-json-serializer/blob/5.0.6_json-serialization-small-overload_0/public/index.php#L27'
        nullSerialization: 'https://github.com/phpbenchmarks/symfony-json-serializer/blob/5.0.6_json-serialization-small-overload_0/public/index.php#L27'
        arraySerialization: 'https://github.com/phpbenchmarks/symfony-json-serializer/blob/5.0.6_json-serialization-small-overload_0/public/index.php#L27'
        objectSerialization: 'https://github.com/phpbenchmarks/symfony-json-serializer/blob/5.0.6_json-serialization-small-overload_0/src/Normalizer/ObjectToSerializeNormalizer.php'
        customSerializers: 'https://github.com/phpbenchmarks/symfony-json-serializer/blob/5.0.6_json-serialization-small-overload_0/src/Normalizer'
coreDependency:
    name: symfony/serializer
    version: 5.0.6
